# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml test



trigger:
- master

pool:
  name: 'Linux-Docker'

container: joneslanglasalle/imagefactory:vsphere

workspace:
  clean: all

variables:
  group: vsphere-uslilvmlabvc01
  vsphereconfig: "./win2016/vsphere-vars-uslilvmlabvc01.json"

steps:
#- bash: echo $(VSPHERE_USERNAME)
- powershell: |
    # Using an input-macro:
    Write-Host "This works: $(VSPHERE_USERNAME)"

    # Using the env var directly:
    #Write-Host "This does not work: $env:MYSECRET"

    # Using the mapped env var:
    Write-Host "This works: $env:VSPHERE_USERNAME"    # Recommended
  env:
    MY_MAPPED_ENV_VAR: $(VSPHERE_USERNAME)

#- task: CmdLine@2
#  displayName: Packer build
#  inputs:
#    script: packer build -color=false -var-file=$(vsphereconfig) ./win2016/windows-base.json 

