# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml test



trigger:
- master

pool:
  name: 'Linux-Docker'

container: joneslanglasalle/imagefactory:vsphere

workspace:
  clean: all

variables:
  group: vsphere-uslilvmlabvc01
  vsphereconfig: "./packer/vsphere-vars-uslilvmlabvc01.json"

steps:
- task: CmdLine@2
  displayName: Testing
  inputs:
    script: |
      echo Testing...
      ls -l

- task: CmdLine@2
  displayName: Packer build
  inputs:
    script: packer build -color=false -var-file=$(vsphereconfig) ./packer/windows-base.json 

