# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml test

trigger:
  - master

jobs:
- job: Build
  timeoutInMinutes: 360

  #pool:
  #  name: 'Linux-Docker'
  pool:
    vmImage: 'ubuntu-16.04'

  container: joneslanglasalle/imagefactory:vsphere1

  workspace:
    clean: all

  variables:
  - group: vsphere-uslilvmlabvc01
  - name: vsphereconfig
    value: "./win2016/vsphere-vars-uslilvmlabvc01.json"
  - name: FRIENDLYNAME
    value: "Windows 2016 Server Datacenter Template"

  steps:
  #- task: CmdLine@2
  #  displayName: Packer build
  #  inputs:
  #    script: |
  #      sed "s/REPLACEME/$(PACKER_PASSWORD)/g" ./win2016/setup/Autounattend.xml.copy > ./win2016/setup/Autounattend.xml
  #      packer build -color=false -var-file=$(vsphereconfig) ./win2016/windows-base.json 
  #  env: {VSPHERE_PASSWORD: $(VSPHERE_PASSWORD), PACKER_PASSWORD: $(PACKER_PASSWORD)}

  - task: CmdLine@2
    displayName: uname
    inputs:
      script: |
        env
        #ls /root/.local/share/powershell/Modules/

  - pwsh: |
      env
      dir
      Connect-VIServer

  #- pwsh: ./win2016/scripts/VmToTemplate.ps1

  - task: Powershell@2
    displayName: Testing
    inputs:
      pwsh: true
      targetType: 'inline'
      script: dir


